version: "3"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-navidrome_server_1
      APP_PORT: 4533
      #PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: deluan/navidrome:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - "/home/umbrel/umbrel/data/storage/downloads/music:/music:ro"   # must be changed in the end
    restart: on-failure
