version: '3.8'

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-duplicati_server_1
      APP_PORT: 8200
      
  server:
    image: linuxserver/duplicati:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      #- ${APP_DATA_DIR}/data/tmp:/tmp
      - ${APP_DATA_DIR}/data/backups:/backups
      - ${APP_DATA_DIR}/data/source:/source
    restart: on-failure
