version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-guacamole_server_1
      APP_PORT: 8080
      #PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: jwetzell/guacamole:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
