version: "3"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-guacamole_server_1
      APP_PORT: 8080

  server:
    image: abesnier/guacamole:latest
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
