version: "2.1"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-readarr_server_1
      APP_PORT: 8787
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/readarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
    
  mac:
    image: getumbrel/media-app-configurator:v1.0.0@sha256:e3d8b18e0186f76dd3f3d4acacc9101b4abbf302d8f2afbb47cdd3879b1a1008
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      DOWNLOAD_CLIENT_API_URL: "http://glimbox-readarr_server_1:8787/api/v3/downloadclient"
      ROOT_FOLDER_API_URL: "http://glimbox-readarr_server_1:8787/api/v3/rootfolder"
      TRANSMISSION_HOST: "transmission_server_1"
      TRANSMISSION_PORT: 9091
      SABNZBD_HOST: "glimbox-sabnzbd_server_1"
      SABNZBD_PORT: 8087
      ROOT_FOLDER: "/downloads/books"
