version: "2"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-filestash_server_1
      APP_PORT: 8334
      
  server:
    image: machines/filestash:latest
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/data/state
    environment:
    - APPLICATION_URL=http://glimbox-filestash_server_1
    #- GDRIVE_CLIENT_ID=<gdrive_client>
    #- GDRIVE_CLIENT_SECRET=<gdrive_secret>
    #- DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://onlyoffice
    restart: on-failure
    
  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver:latest
    restart: always
    security_opt:
      - seccomp:unconfined
