version: "2.1"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-overleaf_server_1
      APP_PORT: 8080

  mongo:
    restart: on-failure
    user: "1000:1000"
    image: mongo:latest
    #container_name: mongo
    expose:
      - 27017
    volumes:
      - ${APP_DATA_DIR}/mongo_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: on-failure
    image: redis:6.2
    #container_name: redis
    user: "1000:1000"
    expose:
      - 6379
    volumes:
      - ${APP_DATA_DIR}/redis_data:/data    
      
  server:
    image: sharelatex/sharelatex:latest
    user: "1000:1000"
    environment:
      - TZ=Etc/UTC
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
        
    ports:
      - 80:80
    links:
      - mongo
      - redis
    stop_grace_period: 60s
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/sharelatex
      
    environment:
      SHARELATEX_APP_NAME: Overleaf Community Edition
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      # Same property, unfortunately with different names in
      # different locations
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: 'true'
      # Disables email confirmation requirement
      EMAIL_CONFIRMATION_DISABLED: 'true'
      # temporary fix for LuaLaTex compiles
      # see https://github.com/overleaf/overleaf/issues/695
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var    
    
