version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: glimbox-dashy_server_1
      APP_PORT: 80

  server:
    image: lissy93/dashy:latest
    user: '1000:1000'
    environment:
      - NODE_ENV=production
    volumes:
      - ${APP_DATA_DIR}/data/config/conf.yml:/app/public/conf.yml
      - ${APP_DATA_DIR}/data/icons:/app/public/item-icons
    restart: on-failure

    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
