version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-jellyseerr_server_1
      APP_PORT: 5055

  server:
    image: 'fallenbagel/jellyseerr:1.5.0'
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure
