version: "2.1"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-grocy_server_1
      APP_PORT: 9283
      #PROXY_AUTH_WHITELIST: "/api/*"
      
  server:
    image: linuxserver/grocy:latest
    user: '1000:1000'
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
