version: "2.1"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-grocy_server_1
      APP_PORT: 9283
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/grocy:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
