version: "2.1"

services:
  app_proxy:
    environment:
      APP_HOST: glimbox-sabnzbd_server_1
      APP_PORT: 8080
      
  server:
    image: linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - ${UMBREL_ROOT}/data/storage/downloads/incomplete:/incomplete-downloads
      #- ${UMBREL_ROOT}/data/storage/downloads/complete:/complete-downloads
    restart: on-failure
